set-window-option -g mouse on
set -g history-limit 30000
#set -g default-terminal "xterm-256color"
#set -a terminal-overrides ",*256col*:RGB"
## make shared clipboard in mosh+tmux work
#set-option -ag terminal-overrides ",xterm-256color:Ms=\\E]52;c;%p2%s\\7"
#
#set -g set-clipboard on


# tmux-256color instead of screen-256color enables italics
set -g default-terminal "tmux-256color"

# Tc enables true color
set -ag terminal-overrides ",*256col*:colors=256:Tc"

# Ms modifies OSC 52 clipboard handling to work with mosh, see
# https://gist.github.com/yudai/95b20e3da66df1b066531997f982b57b
set -ag terminal-overrides "vte*:XT:Ms=\\E]52;c;%p2%s\\7,xterm*:XT:Ms=\\E]52;c;%p2%s\\7"

# enable OSC 52 clipboard
# https://medium.freecodecamp.org/tmux-in-practice-integration-with-system-clipboard-bcd72c62ff7b
set -g set-clipboard on

# use bracketed paste, if the running application (vim/emacs/weechat) has
# sent the terminal code to enable it.
bind-key ] paste-buffer -p

setw -g aggressive-resize on

# http://comments.gmane.org/gmane.emacs.vim-emulation/1557
set -s escape-time 0

bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Drag windows on the status bar
bind-key -n MouseDrag1Status swap-window -d -t=

bind -n C-h last-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "time"
set -g @dracula-show-powerline true

set -g @plugin 'laktak/extrakto'
set -g @extrakto_fzf_tool '/usr/local/google/home/yufanchen/.fzf/bin/fzf'

set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'Morantron/tmux-fingers'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
